// <auto-generated />
using System;
using HorariosConsoleApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HorariosConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190813211549_version1.1.4")]
    partial class Version114
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HorariosConsoleApp.Entities.Dia", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura");

                    b.Property<string>("Nombre");

                    b.HasKey("DiaId");

                    b.ToTable("Dias");

                    b.HasData(
                        new
                        {
                            DiaId = 1,
                            Abreviatura = "L",
                            Nombre = "Lunes"
                        },
                        new
                        {
                            DiaId = 2,
                            Abreviatura = "M",
                            Nombre = "Martes"
                        },
                        new
                        {
                            DiaId = 3,
                            Abreviatura = "X",
                            Nombre = "Miércoles"
                        },
                        new
                        {
                            DiaId = 4,
                            Abreviatura = "J",
                            Nombre = "Jueves"
                        },
                        new
                        {
                            DiaId = 5,
                            Abreviatura = "V",
                            Nombre = "Viernes"
                        },
                        new
                        {
                            DiaId = 6,
                            Abreviatura = "S",
                            Nombre = "Sábado"
                        },
                        new
                        {
                            DiaId = 7,
                            Abreviatura = "D",
                            Nombre = "Domingo"
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Nombre");

                    b.HasKey("EmpleadoId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            EmpleadoId = 1,
                            Apellido = "Perez",
                            Nombre = "Juan"
                        },
                        new
                        {
                            EmpleadoId = 2,
                            Apellido = "Mitnick",
                            Nombre = "Kevin"
                        },
                        new
                        {
                            EmpleadoId = 3,
                            Apellido = "Quezada",
                            Nombre = "Jose"
                        },
                        new
                        {
                            EmpleadoId = 4,
                            Apellido = "Rulfo",
                            Nombre = "Juan"
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.EmpleadoEquipo", b =>
                {
                    b.Property<int>("EmpleadoEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoId");

                    b.Property<int>("EquipoId");

                    b.Property<DateTime>("Fecha");

                    b.HasKey("EmpleadoEquipoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("EmpleadosEquipos");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("EquipoId");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            EquipoId = 1,
                            Nombre = "Zebra"
                        },
                        new
                        {
                            EquipoId = 2,
                            Nombre = "Bravo"
                        },
                        new
                        {
                            EquipoId = 3,
                            Nombre = "Ranger"
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.EquipoHorario", b =>
                {
                    b.Property<int>("EquipoHorarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EquipoId");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("HorarioId");

                    b.HasKey("EquipoHorarioId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("HorarioId");

                    b.ToTable("EquipoHorarios");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HoraDetalle", b =>
                {
                    b.Property<int>("HoraDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Hora");

                    b.Property<int>("HorarioFraccionId");

                    b.Property<int>("TipoHoraId");

                    b.HasKey("HoraDetalleId");

                    b.HasIndex("HorarioFraccionId");

                    b.HasIndex("TipoHoraId");

                    b.ToTable("HoraDetalles");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura");

                    b.Property<string>("Alias");

                    b.Property<string>("Descripcion");

                    b.HasKey("HorarioId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HorarioFraccion", b =>
                {
                    b.Property<int>("HorarioFraccionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiaId");

                    b.Property<TimeSpan>("HoraFin");

                    b.Property<TimeSpan>("HoraInicio");

                    b.Property<int?>("HorarioId");

                    b.HasKey("HorarioFraccionId");

                    b.HasIndex("DiaId");

                    b.HasIndex("HorarioId");

                    b.ToTable("HorarioFraccion");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.TipoHora", b =>
                {
                    b.Property<int>("TipoHoraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<decimal>("PorcentajeExtra");

                    b.HasKey("TipoHoraId");

                    b.ToTable("TipoHoras");

                    b.HasData(
                        new
                        {
                            TipoHoraId = 1,
                            Nombre = "Hora Ordinaria Diura",
                            PorcentajeExtra = 0m
                        },
                        new
                        {
                            TipoHoraId = 2,
                            Nombre = "Hora Ordinaria Nocturna",
                            PorcentajeExtra = 25m
                        },
                        new
                        {
                            TipoHoraId = 3,
                            Nombre = "Hora Extra Diura",
                            PorcentajeExtra = 200m
                        },
                        new
                        {
                            TipoHoraId = 4,
                            Nombre = "Hora Extra Nocturna",
                            PorcentajeExtra = 250m
                        },
                        new
                        {
                            TipoHoraId = 5,
                            Nombre = "Hora Ordinaria Diurna Sabado",
                            PorcentajeExtra = 0m
                        },
                        new
                        {
                            TipoHoraId = 6,
                            Nombre = "Hora Ordinaria Nocturna Sabado",
                            PorcentajeExtra = 25m
                        },
                        new
                        {
                            TipoHoraId = 7,
                            Nombre = "Hora Ordinaria Diurna Domingo",
                            PorcentajeExtra = 150m
                        },
                        new
                        {
                            TipoHoraId = 8,
                            Nombre = "Hora Ordinaria Nocturna Domingo",
                            PorcentajeExtra = 175m
                        },
                        new
                        {
                            TipoHoraId = 9,
                            Nombre = "Hora Extra Diurna Domingo",
                            PorcentajeExtra = 300m
                        },
                        new
                        {
                            TipoHoraId = 10,
                            Nombre = "Hora Extra Nocturna Domingo",
                            PorcentajeExtra = 350m
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.EmpleadoEquipo", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorariosConsoleApp.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.EquipoHorario", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorariosConsoleApp.Entities.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HoraDetalle", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.HorarioFraccion", "HorarioFraccion")
                        .WithMany()
                        .HasForeignKey("HorarioFraccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorariosConsoleApp.Entities.TipoHora", "TipoHora")
                        .WithMany()
                        .HasForeignKey("TipoHoraId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HorarioFraccion", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Dia", "Dia")
                        .WithMany()
                        .HasForeignKey("DiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorariosConsoleApp.Entities.Horario")
                        .WithMany("HorarioFraccion")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
