// <auto-generated />
using System;
using HorariosConsoleApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HorariosConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HorariosConsoleApp.Entities.CambioHorario", b =>
                {
                    b.Property<int>("CambioHorarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmpleadoId");

                    b.Property<string>("Equipo");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<string>("Horario");

                    b.Property<double>("TotalAsueto");

                    b.HasKey("CambioHorarioId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("CambioHorarios");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.DetallePagoEmpleado", b =>
                {
                    b.Property<int>("DetallePagoEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CantidadHoras");

                    b.Property<int?>("PagoEmpleadoId");

                    b.Property<double>("Porcentaje");

                    b.Property<string>("TipoHora");

                    b.HasKey("DetallePagoEmpleadoId");

                    b.HasIndex("PagoEmpleadoId");

                    b.ToTable("DetallePagoEmpleados");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Dia", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura");

                    b.Property<string>("Nombre");

                    b.HasKey("DiaId");

                    b.ToTable("Dias");

                    b.HasData(
                        new
                        {
                            DiaId = 1,
                            Abreviatura = "L",
                            Nombre = "Lunes"
                        },
                        new
                        {
                            DiaId = 2,
                            Abreviatura = "M",
                            Nombre = "Martes"
                        },
                        new
                        {
                            DiaId = 3,
                            Abreviatura = "X",
                            Nombre = "Miércoles"
                        },
                        new
                        {
                            DiaId = 4,
                            Abreviatura = "J",
                            Nombre = "Jueves"
                        },
                        new
                        {
                            DiaId = 5,
                            Abreviatura = "V",
                            Nombre = "Viernes"
                        },
                        new
                        {
                            DiaId = 6,
                            Abreviatura = "S",
                            Nombre = "Sábado"
                        },
                        new
                        {
                            DiaId = 7,
                            Abreviatura = "D",
                            Nombre = "Domingo"
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Codigo");

                    b.Property<int>("EquipoId");

                    b.Property<string>("Nombre");

                    b.Property<decimal>("SalarioBase");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HorarioId");

                    b.Property<string>("Nombre");

                    b.HasKey("EquipoId");

                    b.HasIndex("HorarioId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HoraDetalle", b =>
                {
                    b.Property<int>("HoraDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Hora");

                    b.Property<int>("HorarioFraccionId");

                    b.Property<int?>("HorarioFragmentoId");

                    b.Property<int>("TipoHoraId");

                    b.HasKey("HoraDetalleId");

                    b.HasIndex("HorarioFragmentoId");

                    b.HasIndex("TipoHoraId");

                    b.ToTable("HoraDetalles");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura");

                    b.Property<string>("Alias");

                    b.Property<string>("Descripcion");

                    b.HasKey("HorarioId");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            HorarioId = 1,
                            Abreviatura = "I",
                            Alias = "Azul",
                            Descripcion = "Lunes a viernes de 6:00 am a 2:00 pmSabado de 6:00 am a 10:00 am y 6:00 pm 6:00 am"
                        },
                        new
                        {
                            HorarioId = 2,
                            Abreviatura = "II",
                            Alias = "Rojo",
                            Descripcion = "Lunes a viernes de 2:00 am a 10:00 pmSabado de 10:00 am a 2:00 am y Domingo 6:00 am 6:00 pm"
                        },
                        new
                        {
                            HorarioId = 3,
                            Abreviatura = "III",
                            Alias = "Negro",
                            Descripcion = "Lunes a viernes de 10:00 pm a 6:00 amSabado de 2:00 pm a 6:00 am y Domingo 6:00 pm 6:00 am"
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HorarioFragmento", b =>
                {
                    b.Property<int>("HorarioFragmentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiaId");

                    b.Property<TimeSpan>("HoraFin");

                    b.Property<TimeSpan>("HoraInicio");

                    b.Property<int?>("HorarioId");

                    b.HasKey("HorarioFragmentoId");

                    b.HasIndex("DiaId");

                    b.HasIndex("HorarioId");

                    b.ToTable("HorarioFragmento");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.PagoEmpleado", b =>
                {
                    b.Property<int>("PagoEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dia");

                    b.Property<int?>("EmpleadoId");

                    b.Property<string>("Equipo");

                    b.Property<bool>("EsAsueto");

                    b.Property<DateTime>("FechaPago");

                    b.Property<string>("Horario");

                    b.Property<decimal>("SalarioHora");

                    b.Property<double>("TotalAsueto");

                    b.HasKey("PagoEmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("PagoEmpleados");
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.TipoHora", b =>
                {
                    b.Property<int>("TipoHoraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<decimal>("PorcentajeExtra");

                    b.HasKey("TipoHoraId");

                    b.ToTable("TipoHoras");

                    b.HasData(
                        new
                        {
                            TipoHoraId = 1,
                            Nombre = "Hora Ordinaria Diura",
                            PorcentajeExtra = 0m
                        },
                        new
                        {
                            TipoHoraId = 2,
                            Nombre = "Hora Ordinaria Nocturna",
                            PorcentajeExtra = 25m
                        },
                        new
                        {
                            TipoHoraId = 3,
                            Nombre = "Hora Extra Diura",
                            PorcentajeExtra = 200m
                        },
                        new
                        {
                            TipoHoraId = 4,
                            Nombre = "Hora Extra Nocturna",
                            PorcentajeExtra = 250m
                        },
                        new
                        {
                            TipoHoraId = 5,
                            Nombre = "Hora Ordinaria Diurna Sabado",
                            PorcentajeExtra = 0m
                        },
                        new
                        {
                            TipoHoraId = 6,
                            Nombre = "Hora Ordinaria Nocturna Sabado",
                            PorcentajeExtra = 25m
                        },
                        new
                        {
                            TipoHoraId = 7,
                            Nombre = "Hora Ordinaria Diurna Domingo",
                            PorcentajeExtra = 150m
                        },
                        new
                        {
                            TipoHoraId = 8,
                            Nombre = "Hora Ordinaria Nocturna Domingo",
                            PorcentajeExtra = 175m
                        },
                        new
                        {
                            TipoHoraId = 9,
                            Nombre = "Hora Extra Diurna Domingo",
                            PorcentajeExtra = 300m
                        },
                        new
                        {
                            TipoHoraId = 10,
                            Nombre = "Hora Extra Nocturna Domingo",
                            PorcentajeExtra = 350m
                        });
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.CambioHorario", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.DetallePagoEmpleado", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.PagoEmpleado")
                        .WithMany("DetallePago")
                        .HasForeignKey("PagoEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Empleado", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Equipo", "Equipo")
                        .WithMany("Empleados")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.Equipo", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HoraDetalle", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.HorarioFragmento", "HorarioFragmento")
                        .WithMany()
                        .HasForeignKey("HorarioFragmentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorariosConsoleApp.Entities.TipoHora", "TipoHora")
                        .WithMany()
                        .HasForeignKey("TipoHoraId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.HorarioFragmento", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Dia", "Dia")
                        .WithMany()
                        .HasForeignKey("DiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorariosConsoleApp.Entities.Horario")
                        .WithMany("HorarioFragmentos")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HorariosConsoleApp.Entities.PagoEmpleado", b =>
                {
                    b.HasOne("HorariosConsoleApp.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
